services:
  - type: web
    name: booksite
    runtime: docker
    repo: https://github.com/<твой-username>/booksite
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://*:8080
    healthCheckPath: /health
    autoDeploy: true